[package]
name = "codesignal_rust_practice"
version = "0.1.0"
authors = ["Rohit Sarpotdar <rohi7ns@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
